spring:
  application:
    name: materialized-view

  # Aerospike configuration using Spring Boot starter properties
  aerospike:
    hosts: ${embedded.aerospike.host:localhost}:${embedded.aerospike.port:3000}
    # Connection pooling and client tuning
    # Number of separate connection pools per node to increase concurrency
    connPoolsPerNode: 4
    # Maintain at least this many connections per node in each pool
    minConnsPerNode: 8
    # Cap maximum concurrent connections per node across pools
    maxConnsPerNode: 64
    # Close sockets that have been idle for this duration (ms)
    maxSocketIdle: 600000
    # General timeouts/tending
    timeout: 1000
    tendInterval: 500
    write:
      sendKey: true

  data:
    aerospike:
      namespace: ${embedded.aerospike.namespace:test}
      scans-enabled: true

  cache:
    type: caffeine
    cache-names:
      - productById
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=5m,recordStats

  cloud:
    function:
      definition: processProductChange

    stream:
      bindings:
        processProductChange-in-0:
          destination: product-changes
          content-type: application/*+avro
          group: materialized-view-group
          consumer:
            maxAttempts: 5
            backOffInitialInterval: 1000
            backOffMultiplier: 2.0
            backOffMaxInterval: 15000
            retryableExceptions:
              com.ai.coding.materializedview.domain.exception.InvalidMessageException: false
              com.ai.coding.materializedview.domain.exception.ExternalDependencyException: true
              com.ai.coding.materializedview.domain.exception.PersistenceException: true
        productChangesDlq-out-0:
          destination: product-changes.DLT
          content-type: application/*+avro

      kafka:
        streams:
          binder:
            configuration:
              application.id: materialized-view-app
              bootstrap.servers: localhost:9092
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
              schema.registry.url: http://localhost:8081
              auto.offset.reset: earliest
              processing.guarantee: exactly_once

resilience4j:
  circuitbreaker:
    instances:
      product-commands:
        slidingWindowSize: 50
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - com.ai.coding.materializedview.domain.exception.ExternalDependencyException
          - com.ai.coding.materializedview.domain.exception.PersistenceException
        ignoreExceptions:
          - com.ai.coding.materializedview.domain.exception.InvalidMessageException

logging:
  level:
    com.ai.coding.materializedview: DEBUG
    org.springframework.cloud.stream: INFO
    org.apache.kafka.streams: INFO
